version: '3.3'

volumes:
  pg_data:
  front:
  media:

services:
  db:
    container_name: foodgram-db
    image: postgres:17
    environment:
      - POSTGRES_DB=foodgram
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - DB_NAME=foodgram
      - DB_HOST=localhost
      - DB_PORT=5432
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    container_name: foodgram-back
    image: liquidice64/foodgram_backend:latest
    environment:
      - POSTGRES_DB=foodgram
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - DB_NAME=foodgram
      - DB_HOST=foodgram-db
      - DB_PORT=5432
    volumes:
      - front:/front/
      - media:/media/
    depends_on:
      - db
  frontend:
    container_name: foodgram-front
    image: liquidice64/foodgram_frontend:latest
    volumes:
      - front:/front/
  nginx:
    container_name: foodgram-proxy
    image: nginx:1.25.4-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - front:/front/
      - ./docs/:/front/api/docs/
      - media:/media/
