# Generated by Django 5.2.3 on 2025-06-12 22:36

from django.db import migrations


def load_data(apps, schema_editor):
    import json
    Ingredient = apps.get_model('foodgram', 'Ingredient')
    data_path = 'foodgram/migrations/data/0002_ingredients.json'
    with open(data_path, 'r', encoding='utf-8') as f:
        ingredients_data = json.load(f)
        Ingredient.objects.bulk_create([
            Ingredient(**data)
            for data in ingredients_data
        ])


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_data),
    ]
