# Generated by Django 5.2.3 on 2025-06-13 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0004_locale'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'verbose_name': 'ингредиент рецепта', 'verbose_name_plural': 'Ингредиенты рецептов'},
        ),
    ]
